version: '3.8'

services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antenna_tracker_dev
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true          # vcan/CAN 소켓 접근에 필요
    tty: true
    stdin_open: true
    command: /bin/bash
